### ISSUE TITLE
API call for updating a user's non-custom security groups?

### ISSUE THREAD

**Issue by nhung617** [IronBox/ironboxdx-python#1]
Hi,

Thanks very much for creating this wrapper! It's very helpful.

I was wondering if there is currently a way to add/remove a user to a non-custom security group (i.e. Administrators, Developers, etc.) like for custom groups? If not, are there plans to add that ability in the future?

**Comment by kevinjameslam** [comment]
Not a problem, always strive to make user's lives easier!

**Adding/removing users to non-custom security groups:** 
Originally when threat models for IronBox DX was created, the idea got nixed because we didn't want an attacker who happened to stumble upon API keys that weren't well secured to be able to escalate their privilege on the system (i.e. add themselves or someone else as an admin). So, we forced this as a manual thing that had to be done. 

That said, I think it would be reasonable to add users to groups like Server Side Encrypted (Creators/Readers) via the API as a nice balance.  So add via API to admins and developers (not supported), everything else so long as it's not a privilege group then yes.


Would the above work for your use case? If you're able to share, what does your use case look like?

**Comment by nhung617** [comment]
Hi Kevin,

Thanks so much for your quick and detailed response! 

I'm currently working on a new Identity, Governance and Administration solution at my company that centralizes entitlement gathering/provisioning for employees and we want to be able to automate the assigning of roles for employees that need IronBox, in addition to other apps like Jira and Slack, for example.

I think your solution would definitely work for our use case, since most of our IronBox users should be just container creators/readers. However, I'm still in the process of confirming with my team that this is something we need and will report back when I get confirmation.

**Comment by nhung617** [comment]
Hi again Kevin,

If the functionality you suggested could be implemented, that would awesome. We could definitely use it in our entitlement provisioning workflow. 

Thanks again for your work and help!

**Comment by kevinjameslam** [comment]
Hi Nhung617,

Okay, I'll add this to our next sprint which is starting soon and update here later.

Kevin

**Comment by kevinjameslam** [comment]
@nhung617 Update only so no response needed: this has been implemented and checked into our internal tree. It's working its way through the test passes now and assuming all goes well then should be pushed into production either this weekend or next.

**Comment by kevinjameslam** [comment]
@nhung617 Obviously last weekend didn't work out, had to back out of what was supposed to be minor update. Going to go at it again this weekend, so I'll update when done. Thanks!

**Comment by nhung617** [comment]
@kevinjameslam no worries, I appreciate the updates! thanks!

**Comment by kevinjameslam** [comment]
@nhung617 We should be live now, updated the sample section as well. Thanks!

**Comment by nhung617** [comment]
awesome, it's working. thanks very much again @kevinjameslam !
